# Generated by Django 3.1.2 on 2021-01-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210131_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='post',
            name='intro_uz',
            field=models.TextField(max_length=200, null=True, verbose_name='Введение'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
    ]
